# This rule is not used by the project kubeinfer itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over ai.ruijie.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubeinfer
    app.kubernetes.io/managed-by: kustomize
  name: llmservice-admin-role
rules:
- apiGroups:
  - ai.ruijie.io
  resources:
  - llmservices
  verbs:
  - '*'
- apiGroups:
  - ai.ruijie.io
  resources:
  - llmservices/status
  verbs:
  - get
